@baseUrl = http://localhost:5172

### Register User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Refresh Token
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "BcE61xJ30alUETzBnVhGzrEY78XymPfu2eo7DnEtu4s="
}