// <auto-generated />
using System;
using Idiomind.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Idiomind.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505100352_VariantObjectivesRelation2")]
    partial class VariantObjectivesRelation2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Idiomind.Domain.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.CategoryTranslation", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityId", "LanguageCode");

                    b.ToTable("category_translations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Simulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SituationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VariantId");

                    b.ToTable("simulations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SimulationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sender")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TranslatedContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("simulation_messages", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Situation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("situations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationTranslation", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityId", "LanguageCode");

                    b.ToTable("situation_translations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearningLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PromptInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SituationId");

                    b.ToTable("situation_variants", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SituationVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SituationVariantId");

                    b.ToTable("situation_variant_objectives", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantObjectiveTranslation", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityId", "LanguageCode");

                    b.ToTable("situation_variant_objective_translations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantTranslation", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntityId", "LanguageCode");

                    b.ToTable("situation_variant_translations", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearningLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("NextRecommendedSimulation")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextRecommendedSimulation");

                    b.HasIndex("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Idiomind.Domain.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("Idiomind.Domain.Identity.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Category", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Simulation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Situation", null)
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Idiomind.Domain.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Idiomind.Domain.Simulations.Entities.SituationVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Idiomind.Domain.Simulations.ValueObjects.SimulationCompletedObjective", "CompletedObjectives", b1 =>
                        {
                            b1.Property<Guid>("SimulationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ObjectiveId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SimulationId", "ObjectiveId");

                            b1.HasIndex("ObjectiveId");

                            b1.ToTable("simulation_completed_objectives", (string)null);

                            b1.HasOne("Idiomind.Domain.Simulations.Entities.SituationVariantObjective", null)
                                .WithMany()
                                .HasForeignKey("ObjectiveId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SimulationId");
                        });

                    b.Navigation("CompletedObjectives");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SimulationMessage", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Simulation", null)
                        .WithMany("Messages")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Idiomind.Domain.Simulations.ValueObjects.SimulationMessageFeedback", "Feedback", b1 =>
                        {
                            b1.Property<Guid>("SimulationMessageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Classification")
                                .HasColumnType("integer");

                            b1.Property<string>("Correction")
                                .HasColumnType("text");

                            b1.Property<string>("Explanation")
                                .HasColumnType("text");

                            b1.HasKey("SimulationMessageId");

                            b1.ToTable("simulation_messages");

                            b1.WithOwner()
                                .HasForeignKey("SimulationMessageId");
                        });

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Situation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationTranslation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Situation", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariant", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Situation", null)
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantObjective", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.SituationVariant", null)
                        .WithMany("Objectives")
                        .HasForeignKey("SituationVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantObjectiveTranslation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.SituationVariantObjective", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantTranslation", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.SituationVariant", null)
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.UserProfile", b =>
                {
                    b.HasOne("Idiomind.Domain.Simulations.Entities.Simulation", null)
                        .WithMany()
                        .HasForeignKey("NextRecommendedSimulation")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Idiomind.Domain.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Idiomind.Domain.Identity.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Category", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Simulation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.Situation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariant", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Idiomind.Domain.Simulations.Entities.SituationVariantObjective", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
